### ISSUE TITLE
Cannot compile in stable release (Version 0.19.4) 

### ISSUE THREAD

**Issue by khchen** [zevv/npeg#1]
Error message: .nimble\pkgs\npeg-0.8.0\npeg\buildpatt.nim(48, 22) Error: expected: '}', but got: '{'

**Comment by zevv** [comment]
Hm, funny, there is all kind of syntax errors indeed. Something was fixed in Nim in a big collective commit from Araq (dee8e6e98) which seems to make this work, but not sure what or how.

Fixed now, thanks!

**Comment by khchen** [comment]
After recent commit, fail to compile in stable release, again.

**Comment by zevv** [comment]
Quoting Ward (2019-04-09 13:40:06)

> After recent commit, fail to compile in stable release, again.

Aw, that's too bad, I was fond of that bit of refactoring. I'll revert
again though, and save that for when the next stable Nim is out.

Thanks again
