### ISSUE TITLE
Npeg too heavy for NimVM

### ISSUE THREAD

**Issue by sealmove** [zevv/npeg#15]
Currently the VM program space is 16bit. Npeg uses more than that when passes a non-trivial grammar to analyze. This means NimVM crashes on relatively complex grammars.

Examples of grammars that npeg can't support due to this:
https://play.nim-lang.org/#ix=22KQ
http://ix.io/22KC/nim

**Comment by zevv** [comment]
Working on that, see https://github.com/zevv/Nim/tree/zevv-vmrework

**Comment by sealmove** [comment]
Solved by:
- https://github.com/nim-lang/Nim/pull/12775
- https://github.com/nim-lang/Nim/pull/12777
