### ISSUE TITLE
Captures only work when input is consumed

### ISSUE THREAD

**Issue by sealmove** [zevv/npeg#17]
I think this behavior is somewhat surprising.

```nim
let p = peg o:
  o <- >&1:
    echo len($1)

doAssert p.match("a").ok
```

```
0
```

Possible solutions:
- make it work
- produce a warning/error when `>` is used along with `&`
- mention it in the documentation

**Comment by zevv** [comment]
True, will document. Try instead:

```nim
let p = peg o:
  o <- &>1:
    echo len($1)
```

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by sealmove** [comment]
Ah, this makes sense actually...

**Comment by sealmove** [comment]
Unfortunately you snippet fails with:
```
Error: unhandled exception: Capture out of range, 1 is not in [0..0] [NPegException]
```

**Comment by zevv** [comment]
Sure, it needs this instead:

```
let p = peg o:
  o <- &p   
  p <- >1:
    echo len($1)
```

The reason is that `&` can have no side effects and internally restores the match state and all its captures to the state it was before. I'll add this to the documentation, thanks for reporting!
