### ISSUE TITLE
Feature request: Parse from seq[Token]

### ISSUE THREAD

**Issue by sealmove** [zevv/npeg#20]
Peg is great. One of its advantages is that it's suitable for both lexing and parsing. This doesn't mean it's always preferable to do both of them in one step. Therefore we should provide an interface where the user can either choose to write 1 peg that does both lexing and parsing, or write 2 pegs, 1 for lexing and 1 (which feeds from the previous) for parsing.

To achieve this we need a match() that accepts seq[Token] where Token is user-defined (probably some codegen to generate the match() proc is involve here)

**Comment by zevv** [comment]
Yeaaah, I kind of saw this one coming...

I do agree it would bring NPeg to another level if usability and might also come with nice performance gains, although I'm not sure yet how well this will fit in what there is now, or if it would require serious rewriting.

Let me see if I can gather the motivation to see how much this will cost; I have painted myself in the corner in one or two places when building NPeg, and as long as I don't have to go into these particular corners it might be feasible.

**Comment by zevv** [comment]
I got some basics running, and I'm kind of amazed how few changes were needed for this: I genericized the subject type from `openarray[char]` to `openarray[T]`, and added one opcode to match tokens. The parser now recognizes identifiers in square brackets as tokens, and now I can do:

```
  type Token* = enum                                                          
    One, Two, Three                                                                       
                                                        
  let p = peg2(foo, Token):         
    foo <- [One] * ( [Two] | [Three])     
```

Very much work in progress, but a promising start.

**Comment by sealmove** [comment]
After contemplation, Zevv and I came to the conclusion that the crux is having the indices (relative to the subject stream) of the captures inside a peg code block.

An idea is the following: just as `$` gives "a sequence of the matched tokens" (which happen to be of type `char` and work as one `string`, we can implement `@` which will give "a sequence **of the indices** of the matched tokens".

This suffices for chopping up parsing into two phases. For example:

```Nim
import strutils, sequtils, npeg

type
  Terminal = enum
    tInt
    tStr
    tAdd
    tSub
  Composite = enum
    cOp
  Token = ref object
    case kind: Terminal
    of tInt: intval: int
    of tStr: strval: string
    of tAdd, tSub: discard
  Node = ref object
    case isTerminal: bool
    of true:
      t: Token
    of false:
      case c: Composite
      of cOp:
        left: Node
        op: Token
        right: Node

var tokens: seq[Token]

proc tokenize(subject: string): seq[Token] =
  let l = peg(g, tokens: seq[Token]):
    g   <- *Blank * t * *(*Blank * op * *Blank * t) * *Blank * !1

    t   <- int | str
    op  <- add | sub

    add <- '+':
      tokens.add Token(kind: tAdd)
    sub <- '-':
      tokens.add Token(kind: tSub)
    int <- +Digit:
      tokens.add Token(kind: tInt, intval: parseInt($0))
    str <- +Alnum:
      tokens.add Token(kind: tStr, strval: $0)

  var tokens: seq[Token]
  assert l.match(subject, tokens).ok
  tokens

proc parse(subject: seq[Token]): Node =
  let p = peg(g, stack: seq[Node]):
    g   <- t * *op * !1

    t   <- int | str
    int <- [tInt.int]:
      stack.add Node(isTerminal: true, t: tokens[(@0)[0]])
    str <- [tStr.int]:
      stack.add Node(isTerminal: true, t: tokens[(@0)[0]])
    op  <- >(add | sub) * t:
      stack.add Node(isTerminal: false, c: cOp, left: stack.pop,
                     op: tokens[(@1)[0]], right: stack.pop)

  var node: Node
  assert p.match(subject.mapIt(it.int), node)
  assert stack.len == 1
  stack[0]

let ast = "1 + 2".tokenize.parse
```

**Comment by zevv** [comment]
I've come a long way, but I'm stuck now: I have no clue how to resolve the enum values in the Peg to their corresponding integer values at compile time, like in your above example: `int <- [tInt.int]:`, I would need to be able to find the enum value of `tInt. Any ideas?

**Comment by zevv** [comment]
Ok, this would be easy if the grammar was passed as `typed` to the `peg` macro and friends, but that does not work because it is not valid nim code. NPeg uses `untyped` instead, and then this kind of info gets lost in translation...

**Comment by zevv** [comment]
@sealmove: check out the `refactoring` branch, this works now:

```
  type
    Token* = enum
      tInt
      tAdd
      cAddExpr
    Node = ref object
      case kind: Token
      of tInt:
        intval: int
      of tAdd:
        discard
      of cAddExpr:
        l, r: Node

  proc tokenize(subject: string): seq[Node] =
    let l = peg(g, output: seq[Node]):
      g   <- *Blank * t * *(*Blank * add * *Blank * t) * *Blank * !1
      t   <- int
      int <- +Digit:
        output.add Node(kind: tInt, intval: parseInt($0))
      add  <- '+':
        output.add Node(kind: tAdd)
    assert l.match(subject, result).ok
 
  proc parse(subject: seq[Node]): Node =
    let p = peg2(g, stack: seq[Node]):
      g   <- t * *add * !1
      t   <- int
      int <- [tInt]:
        stack.add subject[(@0)]
      add <- [tAdd] * int:
        stack.add Node(kind: cAddExpr, l: stack.pop, r: stack.pop)
 
    let s = subject.mapIt(it.kind.int)
    var stack: seq[Node]
    assert p.match(s, stack).ok
    assert stack.len == 1
    stack[0]
 
  let ast = "1 + 2".tokenize.parse()
  echo ast.repr

```

**Comment by zevv** [comment]
And even better like this: no globals and no restrictions on types anymore, NPeg can now parse your `seq[Node]` straight away:

```
import npeg, strutils, sequtils

type

  Token* = enum
    tInt
    tAdd
    cAddExpr

  Node = ref object
    case kind: Token
    of tInt:
      intval: int
    of tAdd:
      discard
    of cAddExpr:
      l, r: Node

  State = ref object
    tokens: seq[Node]
    stack: seq[Node]

proc `==`(n: Node, t: Token): bool = n.kind == t

proc `$`(n: Node): string =
  case n.kind
    of tInt: return $n.intVal
    of tAdd: return "+"
    of cAddExpr: return "(" & $n.l & " + " & $n.r & ")"

let lexer = peg(tokens, st: State):
  s      <- *Space
  tokens <- *(s * token) * s
  token  <- int | add
  int    <- +Digit:
    st.tokens.add Node(kind: tInt, intval: parseInt($0))
  add    <- '+':
    st.tokens.add Node(kind: tAdd)

let parser = peg(g, Node, st: State):
  g   <- int * *add * !1
  int <- [tInt]:
    st.stack.add st.tokens[@0]
  add <- [tAdd] * int:
    st.stack.add Node(kind: cAddExpr, r: st.stack.pop, l: st.stack.pop)

var st = State()
assert lexer.match("1 + 2 + 3", st).ok
assert parser.match(st.tokens, st).ok
echo st.stack[0]
``

**Comment by zevv** [comment]
@sealmove: this should work for you, NPeg is now fully generic up to its captures, so the original plan of keeping shadow arrays and `@0` for indexing is not even needed. Let me know if this works for you so I can merge to master and release.

**Comment by zevv** [comment]
Happy happy happy! Json lexer and parser:

```
type
  Token = enum
    tkNull,
    tkBool,
    tkNumber,
    tkString,
    tkComma,
    tkColon,
    tkArrOpen,
    tkArrClose,
    tkObjOpen,
    tkObjClose

  Node = ref object
    case kind: Token
    of tkBool:
      valBool: bool
    of tkNumber:
      valNumber: float
    of tkString:
      valString: string
    else:
      discard

  State = ref object
    nodes: seq[Node]

proc `==`(n: Node, t: Token): bool = n.kind == t

template add(k: untyped) = st.nodes.add Node(kind: k)
template add(k: untyped, e: untyped) = st.nodes.add Node(kind: k, e)

let lexer = peg(nodes, st: State):

  tcomma    <- ',': add(tkComma)
  tcolon    <- ':': add(tkColon)
  tarropen  <- '[': add(tkArrOpen)
  tarrclose <- ']': add(tkArrClose)
  tobjopen  <- '{': add(tkObjOpen)
  tobjclose <- '}': add(tkObjClose)
  tnull     <- "null": add(tkNull)
  ttrue     <- "true": add(tkBool, valBool: true)
  tfalse    <- "false": add(tkBool, valBool: false)
  tnumber   <- >+(Digit | '.'): add(tkNumber, valNumber: parseFloat($1))
  tstring   <- '"' * >*(1-'"') * '"': add(tkString, valString: $1)

  token <- tnull | ttrue | tfalse | tnumber | tstring | tcomma | tcolon |
           tarropen | tarrclose | tobjopen | tobjclose

  nodes <- *Space * *(token * *Space)


let parser = peg(Value, Node, st: State):

  Value <- [tkNumber] | [tkString] | [tkBool] | [tkNull] | Object
  ObjPair <- [tkString] * [tkColon] * Value
  Object <- [tkObjOpen] * ObjPair * *( [tkComma] * ObjPair ) * [tkObjClose]
  Array <- [tkArrOpen] * Value * *( [tkComma] * Value ) * [tkArrClose]

```

**Comment by zevv** [comment]
@sealmove: what do you think? In the case of matching non-strings, captures are still of type `seq[T]`. This complicates the parser with constructs like `($0)[0].value`, although in practice for parsers I think that captures would typically be only one element. It might make sense to change captures to `T` instead of `seq[T]` in this case, and error/assert if making a single capture consisting of more then one element?

**Comment by sealmove** [comment]
> @sealmove: this should work for you, NPeg is now fully generic up to its captures, so the original plan of keeping shadow arrays and `@0` for indexing is not even needed. Let me know if this works for you so I can merge to master and release.

Sadly I don't have time to test it for a couple of days, but as long as you managed to match against a discriminator, it looks awesome! :)

> @sealmove: what do you think? In the case of matching non-strings, captures are still of type `seq[T]`. This complicates the parser with constructs like `($0)[0].value`, although in practice for parsers I think that captures would typically be only one element. It might make sense to change captures to `T` instead of `seq[T]` in this case, and error/assert if making a single capture consisting of more then one element?

Yeah, I was thinking the same, but what if the capture **is** longer than 1 token?

**Comment by zevv** [comment]
Merged to master

**Comment by zevv** [comment]
No more comments received for a month, so I consider this finished. Closing up!
