### ISSUE TITLE
Nim parser generator story and npeg's role

### ISSUE THREAD

**Issue by sealmove** [zevv/npeg#21]
**Intro:**
I realize npeg's original intention was (still is?) to be a nifty tool for parsing relatively simple grammars with pure Nim code. Therefore it's justifiably unfit for larger projects with more complex grammars.

**But why is it unfit?**
Npeg has come a looooong way! Many of its shortcomings are gone. VM problems are gone and recently you can even write grammars that parse from seq of tokens instead of string (#20)!

But well... the syntax is a rather ugly ad-hoc modification of peg. This is of course necessary in order to be accepted by Nim's parser. Nim-compatible syntax comes with several advantages: Firstly it allows you to leverage Nim's parser instead of implementing one yourself, and secondly it allows the user to write his DSL code in a macro block argument (which is cool and convenient). For large projects though you don't want to use such a syntax just so that you can write directly in a macro block argument and would very much prefer to give this up and use special files (e.g. `.npeg` instead of `.nim`) if it meant better syntax.

Another -less important imo, yet worth mentioning- limitation is lack of lexer/parser pipeline. Yes, you can now parse from tokens, but the two steps being separate hurts performance. Ideally lexer and parser should work concurrently.

**What should we do?**
The thing is... there is really no tool to use with Nim for that matter. Projects like Bison or ANTLR don't support Nim. I think this situation is unacceptable, or at least there is work that must be done in this direction. Lastly I list some options to improve the situation:
- contribute to Bison or ANTLR (add Nim support)
- extend npeg
  - add support for reading standard PEG syntax mixed with Nim code from `.npeg`
  - implement lexer/parser pipeline
  - implement at least a linter for `.npeg` files
- keep npeg nifty as it is and begin a new project oriented towards larger scale parsing

Please comment on which one you think is most logical, most preferable, most feasible, easiest.

**Comment by zevv** [comment]
Cut and paste my own comments from #Nim:

```
12:58 < Zevv> my gut feeling is to not pull this into npeg at this time. We should be able to make something 
              that lies on top of it, but I don't think it needs any tight integration
12:58 < Zevv> so I can concentrate on npeg itself and keep it lean and mean
12:59 < Zevv> I think getting to the stage you describe will also require a fair amount of trial and error 
              and experimentation
13:00 < Zevv> I can provide any hooks that might be needed in NPeg, but it does not need to be part of NPeg 
              itself, as I see it now
13:02 < Zevv> also a lot of the complexity npeg has now will not be needed in higher abstraction layers. If 
              you want to make a lexer with the lexer-module-to-be, you don't need to know all about the 
              rest of the stuff - so from that perspecive it also makes sense to separate it. It can use 
              whatever tools under the hood, but you don't need to expose all that
```
