### ISSUE TITLE
What does !1 do? (in the quickstart) [Question]

### ISSUE THREAD

**Issue by thomastay** [zevv/npeg#22]
In the quickstart, there is a line:
```
pairs <- pair * *(',' * pair) * !1
```

I get that this means that pairs is a list of a pair object, followed by 0 or more pairs. But what is the !1 doing there? The only thing I can think of is that it is negating the literal 1.

**Comment by zevv** [comment]
Hi Thomas, the `!1` means "only succeed if there is not 1 character available", and the only situation where this can match is at the end of the input. This is explained in more detail a bit further down in the manual, please refer to the section about the "not predicate". There is also a separate section discussing the `!1` idiom at  https://github.com/zevv/npeg#end-of-string. I do see the confusion, so I will also update the documentation to reflect this in the initial example.
