### ISSUE TITLE
Just wanted to say npeg is great

### ISSUE THREAD

**Issue by rocket111185** [zevv/npeg#42]
Hi, dear developers

Some months ago I started making a concept of a markup language which would be useful for UI design description.

And week ago I started development.
I know that parsing is actually pain, so I decided to take this library for usage.

It's so amazing! It only took 3 days to find out how can I use it and now I have clean code with several rules, which actually can parse the code!

The parser is still in development, but I'm sure I will be able to make first release soon.

Thank you very much! You are great!

**Comment by zevv** [comment]
Thanks for the note, much appreciated!

Marking this issue as "wontfx", though. I guess I'll have to leave it open forever, as we will never be able to fix how great NPeg is.
