### ISSUE TITLE
Memorization & Bryan Ford

### ISSUE THREAD

**Issue by keiviv** [zevv/npeg#44]
Huge thanks for nPEG — love it a lot, even its quirky syntax — as it gets highlighted, unlike common PEG. Love your other work as well.

PEGs creator — Bryan Ford — has a [page](https://bford.info/packrat/) which (besides other things) lists PEG implementations in various languages. I suggest to ask him to add Nim and its both PEG implementations. His email and twitter are at the index.

In my opinion it would also be a good opportunity to poke his brain on implementing some memorization for your amazing nPEG. I know that contacting people is not everyone's favorite thing, but here are some reasons for it:

- He is a relatively young professor — approachable and curious.
- He is the author of packrat — a practical memorization technique. His Master [thesis](https://pdos.csail.mit.edu/~baford/packrat/thesis/thesis.pdf) describes it, and contains a Haskell implementation. The thesis predates PEG by 2 years, so it uses TDPL instead — but it's still helpful to get the practical gist of his idea. The mentioned info [page](https://bford.info/packrat/) has 6 more pdfs on packrat alone, plus more on related topics. Also has links to packrat implementations in Java, Python, Haskell, Scheme, and Ruby — for inspiration and borrowing.
- Even just exchanging *Hello's* with the inventor would be cool, and potentially could be inspiring and helpful.

You might be busy or have other plans, but if there be time to improve nPEG in terms of memorization — contacting the dude can do no harm. 

In any case — thank you, and best wishes.

**Comment by zevv** [comment]
Hey, thanks for the note.

I tried to contact Ford a few years back: I dropped him a mail with a short description of NPeg and a pretty grammar graph, but unfortunately no response as of yet. Let's ping him, he might still pick that up: @bford :)

As for the other subjects, I have a confession to make: I never read up on or implemented a Packrat parser, so I have no idea on how it compares to the VM implementation used by NPeg and I'm afraid Ford will just see me for the fraud I am :) Note that NPeg is basically just an implementation of Ierusalimschy's LPEG in Lua, albeit with an nice extra step of compiling the interpreter VM into native Lua, so there is not very much original work in it.

I basically consider NPeg "done" for now, as I can not think of any more features I would like to add. There are a few rough edges that people occasionally hit, mostly having to do with the API and backtracking, but I have no ideas on how to actually improve these issues at this time.
