### ISSUE TITLE
Streams / resuming

### ISSUE THREAD

**Issue by zevv** [zevv/npeg#5]
NPeg can at this time only match a complete subject string, which does not allow streaming. Find a way to make NPeg resumable without losing performance, which will then allow easy interfacing with Nim streams.

**Comment by Varriount** [comment]
What method is there that makes NPeg streamable (that does compromise performance)?

**Comment by zevv** [comment]
I once made a naive implementation based on streams, but the overhead for using streams  compared to raw string access was dramatic. My guess is that it still would be possible to interface on top of stream, but this will require an additional level of buffering. This also adds complexity because Npeg needs access to the source data to be able to collect captures, which is hard to do if the stream is not seekable.

**Comment by Varriount** [comment]
Hm. 
An ideal implementation would be able to detect points in the parsing logic where previous input data is no longer required, and mark that part of the buffer for removal. Then, a callback procedure could be given to the parsing procedure when more data is required.

That being said, I can imagine such logic being comes to implement. Hm

**Comment by zevv** [comment]
Indeed, something like that would suffice.

This issue actually targets a more generic case, which is not related to streams only: it should allow NPeg to be called on multiple string subjects, while retaining state. I imagine something like giving match() and extra argument to indicate that more data will arrive in the future. Implementation is not trivial though; for example, a literal string match might be cut in half over iterations, and currently there is no state keeping track of that: a string match either fails or succeeds, but can not succeed for only X characters and later retry on the rest of the string.

As for streams, these should then just work as any passed buffers: NPeg could eat chunks from the stream and keep a local copy of each, as long as one or more open captures refer to the contents of that buffer. When captures are consumed by code blocks these blocks could be dropped on the fly, otherwise they will be kept alive until parsing is done and the captures are collected at the end of the match.

**Comment by Varriount** [comment]
What about using an iterator? Yes, there's a performance penalty (at least, for closure iterators), but at least the cooler would track state for you.

**Comment by zevv** [comment]
Iterators would be cool, but that would exclude the JS back end, which would be a shame.

I now have a branch where the parser is now fully resumable: all closures inside the parser have been changed to use a parser state object which keeps track of all the state, and `match()` can now be called repeatedly on new subject data as it comes in. This would fit naturally on the nim `Streams`. 

This only leaves the problem of holding on to parts of the subject which are still (potentially) being captured so they can be collected when the capture closes. Need some more time for experimentation to see what the best way is to solve this.

**Comment by zevv** [comment]
Moved to README 'future directions'
