### ISSUE TITLE
Enhancing parser flexibility: improving type parsing with the push template

### ISSUE THREAD

**Issue by khchen** [zevv/npeg#67]
I have developed a lexer/parser, similar to the example "tests/lexparse.nim", that offers the ability to parse types beyond just strings.

Using the `push` template within the parser has proven to be incredibly useful for achieving this functionality. I made a modification to the codegne.nim file:

```nim
template push(`s`: string) {.used.}
```

I made the following change to expand its capabilities:

```nim
template push(`s`: string|`sType`) {.used.}
```

By implementing this modification, the parser now performs smoothly and accurately.

**Comment by zevv** [comment]
makes sense, I'll put this in, thank you.
